
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

# ============================================================
# 1. PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="AI Loan Risk & Approval Engine",
    page_icon="🏦",
    layout="wide"
)

st.markdown("""
<style>

.main-title {
    font-size: 2.2rem;
    font-weight: 750;
    color: #2563EB;
    margin-bottom: 0;
    user-select: none;
    -webkit-user-select: none;
}


.sub-title {
    font-size: 1rem;
    color: #94A3B8;
    margin-bottom: 20px;
    user-select: none;
    -webkit-user-select: none;
}

</style>
""", unsafe_allow_html=True)

st.markdown(
    '<div class="main-title">🏦 AI Loan Risk & Eligibility Classifier</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="sub-title"></div>',
    unsafe_allow_html=True
)

# ============================================================
# 2. DATASET SETTINGS
# ============================================================

st.sidebar.header("⚙️ Dataset Settings")

n_records = st.sidebar.select_slider(
    "Number of Dataset Records",
    options=[10000, 20000, 50000, 100000],
    value=20000,
    format_func=lambda x: f"{x:,} records"
)

test_size = 0.20

# ============================================================
# 3. GENERATE SYNTHETIC DATASET
# ============================================================

@st.cache_data
def load_data(n):
    rng = np.random.default_rng(42)

    income = rng.integers(20000, 200000, n)
    credit_score = rng.integers(300, 850, n)
    loan_amount = rng.integers(5000, 80000, n)

    income_loan_ratio = income / loan_amount

    # Synthetic loan approval criteria
    approved = (
        (credit_score >= 650) &
        (income_loan_ratio >= 1.5)
    ).astype(int)

    return pd.DataFrame({
        "Income": income,
        "CreditScore": credit_score,
        "LoanAmount": loan_amount,
        "IncomeLoanRatio": income_loan_ratio,
        "Approved": approved
    })


df = load_data(n_records)

FEATURES = ["CreditScore", "IncomeLoanRatio"]
X = df[FEATURES]
y = df["Approved"]

st.sidebar.success(f"Dataset loaded: {len(df):,} records")

# ============================================================
# 4. DATASET OVERVIEW
# ============================================================

st.subheader("📌 Dataset Overview")

approved_count = int((df["Approved"] == 1).sum())
rejected_count = int((df["Approved"] == 0).sum())

m1, m2, m3, m4 = st.columns(4)

m1.metric("Total Records", f"{len(df):,}")
m2.metric("Approved", f"{approved_count:,}")
m3.metric("Rejected", f"{rejected_count:,}")
m4.metric("Features", "4")

st.caption(
    "The dataset is synthetic and generated by the application. "
    "It is not real bank customer data."
)

# ============================================================
# 5. DATA INSPECTOR
# ============================================================

with st.expander("📁 View & Inspect Dataset", expanded=False):

    tab1, tab2, tab3 = st.tabs([
        "Dataset Preview",
        "Statistical Summary",
        "Class Distribution"
    ])

    with tab1:
        st.dataframe(
            df,
            use_container_width=True,
            height=350
        )

        csv_data = df.to_csv(index=False).encode("utf-8")

        st.download_button(
            label="📥 Download Complete Dataset (CSV)",
            data=csv_data,
            file_name=f"loan_data_{len(df)}.csv",
            mime="text/csv"
        )

    with tab2:
        st.write("### Numerical Feature Statistics")
        st.dataframe(
            df.describe().T,
            use_container_width=True
        )

    with tab3:
        class_counts = pd.Series({
            "Rejected": rejected_count,
            "Approved": approved_count
        })

        st.bar_chart(class_counts)

# ============================================================
# 6. TRAINING AND TESTING
# ============================================================

@st.cache_resource
def train_models(n):
    data = load_data(n)

    features = ["CreditScore", "IncomeLoanRatio"]
    X_data = data[features]
    y_data = data["Approved"]

    X_train, X_test, y_train, y_test = train_test_split(
        X_data,
        y_data,
        test_size=0.20,
        random_state=42,
        stratify=y_data
    )

    # Decision Tree classifier
    dt_model = DecisionTreeClassifier(
        max_depth=3,
        random_state=42
    )

    dt_model.fit(X_train, y_train)

    # Gaussian Naive Bayes classifier
    nb_model = GaussianNB()
    nb_model.fit(X_train, y_train)

    dt_preds = dt_model.predict(X_test)
    nb_preds = nb_model.predict(X_test)

    return (
        dt_model,
        nb_model,
        X_test,
        y_test,
        dt_preds,
        nb_preds,
        len(X_train),
        len(X_test)
    )


(
    dt_model,
    nb_model,
    X_test,
    y_test,
    dt_preds,
    nb_preds,
    train_count,
    test_count
) = train_models(n_records)

# ============================================================
# 7. EVALUATION METRICS
# ============================================================

def calculate_metrics(y_true, predictions):
    return {
        "Accuracy": accuracy_score(y_true, predictions),
        "Precision": precision_score(
            y_true, predictions, zero_division=0
        ),
        "Recall": recall_score(
            y_true, predictions, zero_division=0
        ),
        "F1-Score": f1_score(
            y_true, predictions, zero_division=0
        )
    }


dt_metrics = calculate_metrics(y_test, dt_preds)
nb_metrics = calculate_metrics(y_test, nb_preds)

metrics_df = pd.DataFrame({
    "Metric": list(dt_metrics.keys()),
    "Decision Tree": [
        f"{value:.2%}" for value in dt_metrics.values()
    ],
    "Gaussian Naive Bayes": [
        f"{value:.2%}" for value in nb_metrics.values()
    ]
})

# ============================================================
# 8. MODEL PERFORMANCE DASHBOARD
# ============================================================

st.subheader("📊 Model Performance Dashboard")

c1, c2, c3 = st.columns(3)

c1.metric("Training Records", f"{train_count:,}")
c2.metric("Testing Records", f"{test_count:,}")
c3.metric(
    "Decision Tree Accuracy",
    f"{dt_metrics['Accuracy']:.2%}"
)

col_eval, col_pred = st.columns([1.1, 1], gap="large")

with col_eval:

    st.markdown("### Comparative Algorithm Benchmark")

    st.dataframe(
        metrics_df,
        use_container_width=True,
        hide_index=True
    )

    st.markdown("### Confusion Matrices")

    cm_tab1, cm_tab2 = st.tabs([
        "Decision Tree",
        "Gaussian Naive Bayes"
    ])

    with cm_tab1:
        cm_dt = confusion_matrix(
            y_test, dt_preds, labels=[0, 1]
        )

        fig_dt, ax_dt = plt.subplots(figsize=(5, 3.5))

        ConfusionMatrixDisplay(
            confusion_matrix=cm_dt,
            display_labels=["Rejected", "Approved"]
        ).plot(
            ax=ax_dt,
            cmap="Blues",
            colorbar=False
        )

        ax_dt.set_title("Decision Tree Confusion Matrix")
        fig_dt.tight_layout()
        st.pyplot(fig_dt)
        plt.close(fig_dt)

    with cm_tab2:
        cm_nb = confusion_matrix(
            y_test, nb_preds, labels=[0, 1]
        )

        fig_nb, ax_nb = plt.subplots(figsize=(5, 3.5))

        ConfusionMatrixDisplay(
            confusion_matrix=cm_nb,
            display_labels=["Rejected", "Approved"]
        ).plot(
            ax=ax_nb,
            cmap="Greens",
            colorbar=False
        )

        ax_nb.set_title("Gaussian Naive Bayes Confusion Matrix")
        fig_nb.tight_layout()
        st.pyplot(fig_nb)
        plt.close(fig_nb)

    st.caption(
        "Confusion matrix rows represent actual classes; "
        "columns represent predicted classes."
    )

# ============================================================
# 9. INTERACTIVE APPLICANT PREDICTOR
# ============================================================

with col_pred:

    st.markdown("### 🔍 Interactive Applicant Predictor")

    with st.container(border=True):

        user_income = st.number_input(
            "Annual Income (₹)",
            min_value=15000,
            max_value=500000,
            value=75000,
            step=5000
        )

        user_score = st.slider(
            "CIBIL / Credit Score",
            min_value=300,
            max_value=850,
            value=720
        )

        user_loan = st.number_input(
            "Requested Loan Amount (₹)",
            min_value=5000,
            max_value=150000,
            value=30000,
            step=2500
        )

        algo_choice = st.radio(
            "Select Classification Algorithm",
            ["Decision Tree", "Gaussian Naive Bayes"],
            horizontal=True
        )

        if st.button(
            "Evaluate Credit Risk",
            type="primary",
            use_container_width=True
        ):

            income_loan_ratio = user_income / user_loan

            applicant = pd.DataFrame([{
                "CreditScore": user_score,
                "IncomeLoanRatio": income_loan_ratio
            }], columns=FEATURES)

            active_model = (
                dt_model
                if algo_choice == "Decision Tree"
                else nb_model
            )

            prediction = int(
                active_model.predict(applicant)[0]
            )

            approval_index = list(
                active_model.classes_
            ).index(1)

            probability = float(
                active_model.predict_proba(applicant)[0][
                    approval_index
                ]
            )

            st.divider()

            st.write(
                f"**Income-to-loan ratio:** "
                f"{income_loan_ratio:.2f}"
            )

            st.write(
                "**Synthetic approval rule:** Credit score ≥ 650 "
                "and income-to-loan ratio ≥ 1.5"
            )

            if prediction == 1:
                st.success("### ✅ Prediction: Approved")
            else:
                st.error("### ❌ Prediction: Rejected")

            st.write(
                f"**Model-estimated approval probability:** "
                f"{probability:.1%}"
            )

            st.progress(probability)

            # Compare with the rule used to generate the dataset
            rule_prediction = int(
                user_score >= 650 and income_loan_ratio >= 1.5
            )

            if prediction == rule_prediction:
                st.info(
                    "The model prediction matches the synthetic "
                    "approval rule for this applicant."
                )
            else:
                st.warning(
                    "The model prediction differs from the synthetic "
                    "rule. Decision Tree predictions may differ near "
                    "thresholds; Gaussian Naive Bayes learns "
                    "probabilistic class distributions."
                )

            st.caption(
                "Educational demonstration only. This model uses "
                "synthetic data and does not determine real loan "
                "eligibility. Its probability is not a guarantee "
                "of actual approval."
            )

# ============================================================
# 10. FOOTER
# ============================================================

st.divider()

st.caption(
    "AI Loan Risk & Eligibility Classifier | "
    "Built with Python, Streamlit, Pandas, NumPy, "
    "Matplotlib and Scikit-learn"
)
